### PR TITLE
Alpine counter block

### PR DESCRIPTION
**Pull request by luisherranz**
It's still missing the alpine library, which should be enqueued from PHP and only when the block is present.

### CODE REVIEW

**Comment by luisherranz** [comment]
The registration should be something like this:

```php
wp_register_script(
  'AlpineJS',
  'https://unpkg.com/alpinejs@3.9.6/dist/cdn.min.js',
  array(),
  "3.9.6", 
  true // Load it in the footer
);
```

Enqueueing should only happen if the block is present:

```php
wp_enqueue_script( 'AlpineJS' );
```

I'm not sure if we can use `render_callback` or if it's better to use `render_block` for that. Let's see if `render_callback` works and ask later if it's where this should go.

_The script should be deferred, but that's not possible yet, so at least we should load it in the footer. Adam Silverstein has a proposal to add `defer` [here](https://github.com/WordPress/performance/issues/168), but it's not available yet._

**Comment by luisherranz** [comment]
@juanmaguitar can you take care of the enqueuing?

**Comment by juanmaguitar** [comment]
>  can you take care of the enqueuing?

Sure! 👍

**Comment by juanmaguitar** [comment]
I have added the code for now to `register_interactive_block_demos` so it's working but the Alpine library is always loaded. 

- [x] Next step would be loading this library only when the block is present (I need to find out how)

Another thing to fix is 
- [x] loading the Alpine library in the footer

The `true` value at the end of this config object doesn't seem to work (at least in my local WordPress)

```
wp_register_script(
  'AlpineJS',
  'https://unpkg.com/alpinejs@3.9.6/dist/cdn.min.js',
  array(),
  "3.9.6", 
  true // Load it in the footer
);
```

**Comment by luisherranz** [comment]
Everything should be working fine now. Merging this 🙂

**Pull request merged**
